travis:
  secure:
    BINSTAR_TOKEN: IoWSA/zPlhhoMpykA/qd6PJBmdHfp/zj5/2pRzp2hzAmT3y0dkVzoFzAexJ7KbNAM7soed9GStcJ4VAC/rme4RWtkATcrQEi7JbIcRPkRBgD6JbbvaVYjgmkv8u9zDfh1OHAZkVeeJKlc/oKbcxtl7xcgk6BLnq80dCfKPluO855+MWexFINCV0GScYvYSwwkCDOG9CImCeO6Qqkwzqk9BU0j02bpGa4cVM3ZnWvPlb1aoqH/Fq3cXjm/PZkrVUsWWxqQh1SrjG7zwM8MJ7qEjMacnKQhV5VVLtnkhrDrFJetdE+qDDABDvApwR6RhAgdiDHB14jS1i2ijos06Sc13R3lUM4ADpnB2RYmeK8xxfwIbkDkV3YSfVjT+//OzQBdtaxSIjqiMzvegj9a+geuL+sYqoZIV3Wh3MtsKAb47SipPD7Ur+yqtYwdUviGhoEbIuYD3VDQ+R/EIBIhmPHM69wqOOOlvmG9aPrQVDbjSSKzwIGSfjBwWG1Jd1G4Uf7EFSwhFuSwnJv8m4cjnHe+op4t/WdUo0xqwhe1crMdczmko+hnFYJP6hqyznv1u9XdFnDrqggQSW+Ji193CZ7ISao5tZs7pUnT5ydc7T6zEkcc6qN6UHrlKVk2PiVRuDuf94VaZIpcyz3s0DISCAThWgFrk93OC/42hcapS8tbFs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
